### ISSUE TITLE
Is it time to update the dependencies again?

### ISSUE THREAD

**Issue by munntjlx** [Szymongib/bookmark#4]
Just curious

**Comment by Szymongib** [comment]
Yeah, probably will be good to do that. I'll look into it on the weekend.

**Comment by munntjlx** [comment]
FYI I love this project! any way to donate or coffeemoney?

**Comment by Szymongib** [comment]
> FYI I love this project! any way to donate or coffeemoney?

Thanks, I am glad you like it 😄 That is enough of a contribution 😉

**Comment by munntjlx** [comment]
Just a Christmas THANK YOU for a great program! Simple and you don't change it every 10 nanoseconds!
