### ISSUE TITLE
Version # is wrong

### ISSUE THREAD

**Issue by munntjlx** [Szymongib/bookmark#7]
I just got 0.2.1 and the version prints the 'old 0.1.x' when I do bookmark --release. Great to see new verison!

**Comment by Szymongib** [comment]
Ah thanks, good catch, will fix it 👍

**Comment by Szymongib** [comment]
Should be closed with https://github.com/Szymongib/bookmark/commit/38a8503a1dafdb65431fcc666e49fc33248da113
